apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tekton-app-backend
  template:
    metadata:
      labels:
        app: tekton-app-backend
    spec:
      containers:
        - name: tekton-app-backend
          image: webapp:1
          # for local development against minikube registry
          #imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
  labels:
    app: backend-app-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3000
      targetPort: 3000
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: tekton-app-backend
